server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    location = /env-config.js {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|mjs|jpg|svg|png|gif|ico|woff|woff2)$ {
        
        if ($request_filename ~* \.mjs$) {
            add_header Content-Type "application/javascript";
        }
        
        expires 1y;
        add_header Cache-Control "public";
    }
}
